from typing import List


class EvaluationAborted(RuntimeError):
    def __init__(self, *args): ...

class InvalidTranslation(ValueError):
    def __init__(self, *args): ...


class DelayedExceptions(Exception):
    exceptions: List[Exception]

    def __init__(self): ...

    def __len__(self) -> int: ...

    def __bool__(self) -> bool: ...

    def add(self, exception: Exception): ...

    def clear(self): ...

    def _print_exceptions(self) -> str: ...

