from bs4.element import Tag
from lxml.etree import _Element
from tinycss2.ast import Declaration

from utils.color_converter import Color

def strip(ls: list) -> list: ...

class CssParsingError(Exception): ...

def _get_xpath(selector: str) -> str: ...

class Rule:
    selector: list
    selector_str: str
    xpath: str
    pseudo: str | None
    name: str
    value: list
    important: bool
    specificity: tuple[int, int, int]
    value_str: str
    color: Color | None

    def __init__(self, selector: list, content: Declaration): ...
    def is_color(self) -> bool: ...
    def has_color(self, color: str) -> bool: ...
    def compare_to(self, value: str | None = None, important: bool | None = None, any_order: bool = False) -> bool: ...

def calc_specificity(selector_str: str) -> tuple[int, int, int]: ...

class Rules:
    root: _Element
    rules: list
    map: dict

    def __init__(self, css_content: str): ...
    def __len__(self) -> int: ...
    def find(self, root: _Element, solution_element: _Element, key: str, pseudo: str | None = None) -> Rule | None: ...
    def find_all(self, root: _Element, solution_element: _Element) -> dict[str, Rule]: ...
    def find_by_css_selector(self, css_selector: str, key: str) -> Rule | None: ...

class AmbiguousXpath(Exception): ...
class ElementNotFound(Exception): ...

class CssValidator:
    root: _Element | None
    rules: Rules
    xpaths: dict

    def __init__(self, html: str): ...
    def __bool__(self): ...
    def get_xpath_soup(self, element: Tag) -> str: ...
    def _get_xpath_soup(self, element: Tag) -> str: ...
    def find(self, element: Tag, key: str, pseudo: str | None = None) -> Rule | None: ...
    def find_by_css_selector(self, css_selector: str, key: str) -> Rule | None: ...
