from abc import ABC
from enum import StrEnum
from types import SimpleNamespace, TracebackType

class ErrorType(StrEnum):
    INTERNAL_ERROR = ...
    COMPILATION_ERROR = ...
    MEMORY_LIMIT_EXCEEDED = ...
    TIME_LIMIT_EXCEEDED = ...
    OUTPUT_LIMIT_EXCEEDED = ...
    RUNTIME_ERROR = ...
    WRONG = ...
    WRONG_ANSWER = ...
    CORRECT = ...
    CORRECT_ANSWER = ...

class MessagePermission(StrEnum):
    STUDENT = ...
    STAFF = ...
    ZEUS = ...

class MessageFormat(StrEnum):
    PLAIN = ...
    TEXT = ...
    HTML = ...
    MARKDOWN = ...
    CALLOUT = ...
    CALLOUT_INFO = ...
    CALLOUT_WARNING = ...
    CALLOUT_DANGER = ...
    CODE = ...
    SQL = ...

class AnnotationSeverity(StrEnum):
    ERROR = ...
    WARNING = ...
    INFO = ...

class DodonaException(Exception):
    status: dict[str, str]
    message: Message | None

    def __init__(self, status: dict[str, str], *args, **kwargs): ...

class DodonaCommand(ABC):
    start_args: SimpleNamespace
    close_args: SimpleNamespace

    def __init__(self, **kwargs): ...
    def name(self) -> str: ...
    def start_msg(self) -> dict | None: ...
    def close_msg(self) -> dict | None: ...
    @staticmethod
    def __print_command(result: None | dict): ...
    def __enter__(self) -> SimpleNamespace: ...
    def handle_dodona_exception(self, exception: DodonaException) -> bool: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool: ...

class DodonaCommandWithAccepted(DodonaCommand):
    def handle_dodona_exception(self, exception: DodonaException) -> bool: ...

class DodonaCommandWithStatus(DodonaCommandWithAccepted):
    def handle_dodona_exception(self, exception: DodonaException) -> bool: ...

class Judgement(DodonaCommandWithStatus):
    def handle_dodona_exception(self, exception: DodonaException) -> bool: ...

class Tab(DodonaCommand):
    def __init__(self, title: str, **kwargs): ...

class Context(DodonaCommandWithAccepted):
    pass

class TestCase(DodonaCommandWithAccepted):
    def __init__(self, *args, **kwargs): ...

class Test(DodonaCommandWithStatus):
    def __init__(self, description: str, expected: str, **kwargs): ...

class Message(DodonaCommand):
    def __init__(self, *args, **kwargs): ...
    def start_msg(self) -> dict: ...
    def close_msg(self) -> None: ...

class Annotation(DodonaCommand):
    def __init__(self, row: int, text: str, **kwargs): ...
    def start_msg(self) -> dict | None: ...
    def close_msg(self) -> None: ...

class SafeAnnotation(Annotation):
    """Annotation that isn't displayed for negative line numbers"""

    def __init__(self, row: int, text: str, **kwargs):
        super().__init__(row=row, text=text, **kwargs)

    def start_msg(self) -> dict | None: ...
